# Generated by Django 4.1.7 on 2023-02-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='channel',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
